-- Supabase schema for the accounting app
-- Run with `supabase db push` or paste into the SQL editor.

create extension if not exists "pgcrypto";
create extension if not exists "uuid-ossp";

create or replace function public.handle_updated_at()
returns trigger
language plpgsql
as $$
begin
    new.updated_at = timezone('utc', now());
    return new;
end;
$$;

create table if not exists public.companies (
    id bigint generated by default as identity primary key,
    name text not null,
    business_number text not null unique,
    hst_number text,
    hst_registered boolean not null default false,
    fiscal_year_end date not null,
    small_business_rate numeric(5,4) not null default 0.1500,
    hst_rate numeric(5,4) not null default 0.1300,
    created_at timestamptz not null default timezone('utc', now()),
    updated_at timestamptz not null default timezone('utc', now())
);

create table if not exists public.profiles (
    id bigint generated by default as identity primary key,
    auth_user_id uuid not null unique references auth.users (id) on delete cascade,
    email text not null unique,
    full_name text,
    role text not null default 'viewer' check (role in ('admin','accountant','viewer')),
    company_id bigint references public.companies (id) on delete set null,
    created_at timestamptz not null default timezone('utc', now()),
    updated_at timestamptz not null default timezone('utc', now())
);

create table if not exists public.clients (
    id bigint generated by default as identity primary key,
    name text not null,
    contact_person text,
    email text,
    phone text,
    address text,
    hst_exempt boolean not null default false,
    company_id bigint not null references public.companies (id) on delete cascade,
    created_at timestamptz not null default timezone('utc', now()),
    updated_at timestamptz not null default timezone('utc', now())
);

create table if not exists public.invoices (
    id bigint generated by default as identity primary key,
    invoice_number text not null unique,
    client_id bigint not null references public.clients (id) on delete restrict,
    issue_date date not null,
    due_date date not null,
    subtotal numeric(12,2) not null,
    hst_amount numeric(12,2) not null default 0,
    total numeric(12,2) not null,
    status text not null default 'draft' check (status in ('draft','sent','paid','overdue','cancelled')),
    paid_date date,
    description text,
    company_id bigint not null references public.companies (id) on delete cascade,
    created_at timestamptz not null default timezone('utc', now()),
    updated_at timestamptz not null default timezone('utc', now())
);

create table if not exists public.invoice_items (
    id bigint generated by default as identity primary key,
    invoice_id bigint not null references public.invoices (id) on delete cascade,
    description text not null,
    quantity numeric(12,2) not null,
    unit_price numeric(12,2) not null,
    total numeric(12,2) not null,
    created_at timestamptz not null default timezone('utc', now()),
    updated_at timestamptz not null default timezone('utc', now())
);

create table if not exists public.expense_categories (
    id bigint generated by default as identity primary key,
    name text not null,
    description text,
    company_id bigint references public.companies (id) on delete cascade,
    created_at timestamptz not null default timezone('utc', now()),
    updated_at timestamptz not null default timezone('utc', now())
);

create table if not exists public.expenses (
    id bigint generated by default as identity primary key,
    description text not null,
    category_id bigint not null references public.expense_categories (id) on delete restrict,
    amount numeric(12,2) not null,
    hst_paid numeric(12,2) not null default 0,
    expense_date date not null,
    receipt_attached boolean not null default false,
    paid_by text not null default 'corp' check (paid_by in ('corp','owner')),
    company_id bigint not null references public.companies (id) on delete cascade,
    created_at timestamptz not null default timezone('utc', now()),
    updated_at timestamptz not null default timezone('utc', now())
);

create table if not exists public.expense_files (
    id bigint generated by default as identity primary key,
    expense_id bigint not null references public.expenses (id) on delete cascade,
    storage_path text not null, -- e.g. expense-files/company-id/uuid.pdf
    original_name text not null,
    mime_type text not null,
    file_size integer not null,
    company_id bigint not null references public.companies (id) on delete cascade,
    created_at timestamptz not null default timezone('utc', now())
);

create table if not exists public.dividends (
    id bigint generated by default as identity primary key,
    amount numeric(12,2) not null,
    declaration_date date not null,
    payment_date date,
    status text not null default 'declared' check (status in ('declared','paid')),
    notes text,
    company_id bigint not null references public.companies (id) on delete cascade,
    created_at timestamptz not null default timezone('utc', now()),
    updated_at timestamptz not null default timezone('utc', now())
);

create table if not exists public.income_entries (
    id bigint generated by default as identity primary key,
    description text not null,
    amount numeric(12,2) not null,
    hst_amount numeric(12,2) not null default 0,
    total numeric(12,2) not null,
    income_type text not null check (income_type in ('client','capital','other')),
    client_id bigint references public.clients (id) on delete set null,
    income_date date not null,
    company_id bigint not null references public.companies (id) on delete cascade,
    created_at timestamptz not null default timezone('utc', now()),
    updated_at timestamptz not null default timezone('utc', now())
);

create table if not exists public.hst_payments (
    id bigint generated by default as identity primary key,
    amount numeric(12,2) not null,
    payment_date date not null,
    period_start date not null,
    period_end date not null,
    reference text,
    notes text,
    company_id bigint not null references public.companies (id) on delete cascade,
    created_at timestamptz not null default timezone('utc', now()),
    updated_at timestamptz not null default timezone('utc', now())
);

create table if not exists public.tax_returns (
    id bigint generated by default as identity primary key,
    fiscal_year integer not null,
    gross_income numeric(14,2) not null default 0,
    total_expenses numeric(14,2) not null default 0,
    net_income_before_tax numeric(14,2) not null default 0,
    small_business_tax numeric(14,2) not null default 0,
    net_income_after_tax numeric(14,2) not null default 0,
    hst_collected numeric(14,2) not null default 0,
    hst_paid numeric(14,2) not null default 0,
    hst_remittance numeric(14,2) not null default 0,
    retained_earnings numeric(14,2) not null default 0,
    company_id bigint not null references public.companies (id) on delete cascade,
    created_at timestamptz not null default timezone('utc', now()),
    updated_at timestamptz not null default timezone('utc', now()),
    unique(company_id, fiscal_year)
);

create table if not exists public.capital_assets (
    id bigint generated by default as identity primary key,
    description text not null,
    category_id bigint references public.expense_categories (id),
    purchase_date date not null,
    purchase_amount numeric(14,2) not null,
    hst_paid numeric(14,2) not null default 0,
    total_cost numeric(14,2) not null,
    cca_class text not null,
    cca_rate numeric(5,4) not null,
    depreciable_amount numeric(14,2) not null,
    accumulated_depreciation numeric(14,2) not null default 0,
    book_value numeric(14,2) not null,
    disposal_date date,
    disposal_amount numeric(14,2),
    paid_by text not null default 'corp' check (paid_by in ('corp','owner')),
    receipt_attached boolean not null default false,
    company_id bigint not null references public.companies (id) on delete cascade,
    created_at timestamptz not null default timezone('utc', now()),
    updated_at timestamptz not null default timezone('utc', now())
);

create table if not exists public.depreciation_entries (
    id bigint generated by default as identity primary key,
    capital_asset_id bigint not null references public.capital_assets (id) on delete cascade,
    fiscal_year integer not null,
    depreciation_amount numeric(14,2) not null,
    is_half_year_rule boolean not null default false,
    entry_date date not null,
    company_id bigint not null references public.companies (id) on delete cascade,
    created_at timestamptz not null default timezone('utc', now()),
    updated_at timestamptz not null default timezone('utc', now()),
    unique(capital_asset_id, fiscal_year)
);

create table if not exists public.owner_payments (
    id bigint generated by default as identity primary key,
    description text not null,
    amount numeric(12,2) not null,
    payment_date date not null,
    payment_type text not null check (payment_type in ('reimbursement','loan_repayment','other')),
    reference text,
    notes text,
    company_id bigint not null references public.companies (id) on delete cascade,
    created_at timestamptz not null default timezone('utc', now()),
    updated_at timestamptz not null default timezone('utc', now())
);

create table if not exists public.cca_classes (
    id bigint generated by default as identity primary key,
    class_number text not null unique,
    description text not null,
    rate numeric(5,4) not null,
    created_at timestamptz not null default timezone('utc', now()),
    updated_at timestamptz not null default timezone('utc', now())
);

create table if not exists public.personal_finance_configs (
    id bigint generated by default as identity primary key,
    personal_finance_api_url text not null,
    personal_finance_api_key text not null,
    user_id uuid not null references auth.users (id) on delete cascade,
    is_enabled boolean not null default true,
    created_at timestamptz not null default timezone('utc', now()),
    updated_at timestamptz not null default timezone('utc', now())
);

drop trigger if exists trg_companies_updated on public.companies;
create trigger trg_companies_updated
    before update on public.companies
    for each row execute procedure public.handle_updated_at();

drop trigger if exists trg_profiles_updated on public.profiles;
create trigger trg_profiles_updated
    before update on public.profiles
    for each row execute procedure public.handle_updated_at();

drop trigger if exists trg_clients_updated on public.clients;
create trigger trg_clients_updated
    before update on public.clients
    for each row execute procedure public.handle_updated_at();

drop trigger if exists trg_invoices_updated on public.invoices;
create trigger trg_invoices_updated
    before update on public.invoices
    for each row execute procedure public.handle_updated_at();

drop trigger if exists trg_invoice_items_updated on public.invoice_items;
create trigger trg_invoice_items_updated
    before update on public.invoice_items
    for each row execute procedure public.handle_updated_at();

drop trigger if exists trg_expense_categories_updated on public.expense_categories;
create trigger trg_expense_categories_updated
    before update on public.expense_categories
    for each row execute procedure public.handle_updated_at();

drop trigger if exists trg_expenses_updated on public.expenses;
create trigger trg_expenses_updated
    before update on public.expenses
    for each row execute procedure public.handle_updated_at();

drop trigger if exists trg_dividends_updated on public.dividends;
create trigger trg_dividends_updated
    before update on public.dividends
    for each row execute procedure public.handle_updated_at();

drop trigger if exists trg_income_entries_updated on public.income_entries;
create trigger trg_income_entries_updated
    before update on public.income_entries
    for each row execute procedure public.handle_updated_at();

drop trigger if exists trg_hst_payments_updated on public.hst_payments;
create trigger trg_hst_payments_updated
    before update on public.hst_payments
    for each row execute procedure public.handle_updated_at();

drop trigger if exists trg_tax_returns_updated on public.tax_returns;
create trigger trg_tax_returns_updated
    before update on public.tax_returns
    for each row execute procedure public.handle_updated_at();

drop trigger if exists trg_capital_assets_updated on public.capital_assets;
create trigger trg_capital_assets_updated
    before update on public.capital_assets
    for each row execute procedure public.handle_updated_at();

drop trigger if exists trg_depreciation_entries_updated on public.depreciation_entries;
create trigger trg_depreciation_entries_updated
    before update on public.depreciation_entries
    for each row execute procedure public.handle_updated_at();

drop trigger if exists trg_owner_payments_updated on public.owner_payments;
create trigger trg_owner_payments_updated
    before update on public.owner_payments
    for each row execute procedure public.handle_updated_at();

drop trigger if exists trg_cca_classes_updated on public.cca_classes;
create trigger trg_cca_classes_updated
    before update on public.cca_classes
    for each row execute procedure public.handle_updated_at();

drop trigger if exists trg_personal_finance_configs_updated on public.personal_finance_configs;
create trigger trg_personal_finance_configs_updated
    before update on public.personal_finance_configs
    for each row execute procedure public.handle_updated_at();

